# Generated by Django 4.1 on 2022-11-23 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_app', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='items',
        ),
    ]
