# Generated by Django 4.1 on 2022-11-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_app', '0004_rename_item_order_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('coupon_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('percent_off', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
