# Generated by Django 4.1 on 2022-11-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_app', '0005_discount_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discount',
            name='coupon_id',
            field=models.CharField(max_length=64),
        ),
    ]
